### PR TITLE
update github action

### PR DESCRIPTION
**Pull request by jxchen01**
add python 3.9 and macos-11.0 in the build system grid

### CODE REVIEW

**Comment by jxchen01** [comment]
@heeler , it looks like the build for macos-11.0 failed even without spitting out any error message. Suggestions? Any idea?

**Comment by heeler** [comment]
Ok this changed on us. So macos-11.0 is technically in preview. If we added it right away it would work but because it's preview they've limited it to the initial users that already set it up. In a few weeks I suspect it will be back. Sorry you spent time on this but for now just add 3.9 and remove macos-11.0 and I'll put it in as a feature request so it get's added back when they make it available to everyone.

**Comment by heeler** [comment]
This case is an exception but generally speaking, you don't want to add reviewers to your PR until you have your checks passing.

**Comment by jxchen01** [comment]
> Ok this changed on us. So macos-11.0 is technically in preview. If we added it right away it would work but because it's preview they've limited it to the initial users that already set it up. In a few weeks I suspect it will be back. Sorry you spent time on this but for now just add 3.9 and remove macos-11.0 and I'll put it in as a feature request so it get's added back when they make it available to everyone.

i just realize that supporting python 3.9 may need some extra work. scikit-image has a breaking release 0.18.0, which seems to be the first version supporting python 3.9. However, scikit-image 0.18.0 also breaks our unit-test, which means some changes in this version cause some function generates output different from previous version. So, currently, we require scikit-image<0.18.0 while we are trying to figure out which change causes the issue. Before we clear up this issue, we cannot support python 3.9 yet. 

So, I am gonna close this PR, and add a feature request for supporting python 3.9. 

What do you think? @heeler

**Comment by heeler** [comment]
@jxchen01 you can either close the PR and keep working on it or keep it open and then Add reviewers once you feel it's ready to go, either works.

We will need 3.9 support ASAP thought.

**Pull request closed without merging**
