### PR TITLE
Feature/provide struct thumbnails

### PR DESCRIPTION
**Pull request by yrkim98**
Embedding thumbnail images in our python package. For https://github.com/AllenCell/napari-aicssegmentation/issues/35

### CODE REVIEW

**Review by schoinh — COMMENTED** [review]
Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.

**Comment by jxchen01** [comment]
> Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.

I think a possible way is simply read the two images and do something like `np.concat( (img_pre, img_psot), axis=1)`. This could stitch them under the hook, and Qt only needs to worry about a single image.

**Comment by yrkim98** [comment]
> Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.

I proposed this two weeks ago when we were initially talking about this issue during our backlog grooming- Sylvain mentioned that that would be too much. I can implement this though.

**Comment by Aerendel** [comment]
> > Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.
> 
> I proposed this two weeks ago when we were initially talking about this issue during our backlog grooming- Sylvain mentioned that that would be too much. I can implement this though.

@schoinh sorry, forgot to bring you into that discussion. My thinking was that it's more flexible to just have the images separately (for Jianxu to reuse elsewhere, and in case any of this gets redesigned / tweaked in the future) and deal with it in the UI. I believe we can just have 2 buttons instead of 1 that connect to the same event and it would look the same. If it ends up being too much work for whatever reason, we can revisit.

**Comment by schoinh** [comment]
> > > Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.
> > 
> > 
> > I proposed this two weeks ago when we were initially talking about this issue during our backlog grooming- Sylvain mentioned that that would be too much. I can implement this though.
> 
> @schoinh sorry, forgot to bring you into that discussion. My thinking was that it's more flexible to just have the images separately (for Jianxu to reuse elsewhere, and in case any of this gets redesigned / tweaked in the future) and deal with it in the UI. I believe we can just have 2 buttons instead of 1 that connect to the same event and it would look the same. If it ends up being too much work for whatever reason, we can revisit.

This sounds like a design decision. Currently the specs have the images side by side with no spacing, on a single button. @thao-do are you ok with having 2 buttons that do the same thing, side by side, instead of 1 big button per workflow?

**Comment by jxchen01** [comment]
> > > > Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.
> > > 
> > > 
> > > I proposed this two weeks ago when we were initially talking about this issue during our backlog grooming- Sylvain mentioned that that would be too much. I can implement this though.
> > 
> > 
> > @schoinh sorry, forgot to bring you into that discussion. My thinking was that it's more flexible to just have the images separately (for Jianxu to reuse elsewhere, and in case any of this gets redesigned / tweaked in the future) and deal with it in the UI. I believe we can just have 2 buttons instead of 1 that connect to the same event and it would look the same. If it ends up being too much work for whatever reason, we can revisit.
> 
> This sounds like a design decision. Currently the specs have the images side by side with no spacing, on a single button. @thao-do are you ok with having 2 buttons that do the same thing, side by side, instead of 1 big button per workflow?

I totally forgot last night... Actually, https://scikit-image.org/docs/stable/api/skimage.util.html#skimage.util.montage   this funciton can help you easily stitch your images into whatever way you want, with or without white gap, with big or small gap, stictching horizontally or vertically, etc... very easy to use. @schoinh

**Comment by schoinh** [comment]
> > > > > Do we only have separate images (pre and post)? I would love a "both" option which is a single png with before and after stitched together, otherwise I'll have to figure out in Qt how to stitch 2 images together... I'm not sure where it would be easier to do that operation, here or in Qt.
> > > > 
> > > > 
> > > > I proposed this two weeks ago when we were initially talking about this issue during our backlog grooming- Sylvain mentioned that that would be too much. I can implement this though.
> > > 
> > > 
> > > @schoinh sorry, forgot to bring you into that discussion. My thinking was that it's more flexible to just have the images separately (for Jianxu to reuse elsewhere, and in case any of this gets redesigned / tweaked in the future) and deal with it in the UI. I believe we can just have 2 buttons instead of 1 that connect to the same event and it would look the same. If it ends up being too much work for whatever reason, we can revisit.
> > 
> > 
> > This sounds like a design decision. Currently the specs have the images side by side with no spacing, on a single button. @thao-do are you ok with having 2 buttons that do the same thing, side by side, instead of 1 big button per workflow?
> 
> I totally forgot last night... Actually, https://scikit-image.org/docs/stable/api/skimage.util.html#skimage.util.montage this funciton can help you easily stitch your images into whatever way you want, with or without white gap, with big or small gap, stictching horizontally or vertically, etc... very easy to use. @schoinh

Thanks @jxchen01 ! This sounds promising...

**Review by schoinh — APPROVED** [review]

**Pull request merged**
